### ISSUE TITLE
Add "Undo" snackbar

### ISSUE THREAD

**Issue by bikram-agarwal** [adithya321/Countdown#2]
I'm on the app's main page where it shows all the countdowns. I accidentally swipe away one event. There's no way to undo that. I have to tap + and add it again from calendar.

Instead, when an event gets swiped away, please show a snackbar at the bottom with "undo" button.

[Here are some examples of snackbar](https://material.io/guidelines/components/snackbars-toasts.html#snackbars-toasts-specs).

**Comment by adithya321** [comment]
Fixed in [15fa3fc303673e3336ae48f501d269c9d54d2ef2](https://github.com/adithya321/Countdown/commit/15fa3fc303673e3336ae48f501d269c9d54d2ef2)
