### ISSUE TITLE
Options to delete events from "Past Events" list

### ISSUE THREAD

**Issue by bikram-agarwal** [adithya321/Countdown#3]
Just like Future event countdowns were showing all events in my calendar earlier, past event count-ups are showing all past events from my calendar. And I am not able to swipe to delete them either. 

1. Please let the user swipe to delete events from the past event count-ups.
2. Add a "Delete All" option here.
3. Don't populate this list with all events from calendar. This list too should have only those events that the user had explicitly added earlier in the "Future event count-down" list.

**Comment by adithya321** [comment]
Fixed by commit [278881153354df35bdb0281065d672a59d322f43](https://github.com/adithya321/Countdown/commit/278881153354df35bdb0281065d672a59d322f43)
