### ISSUE TITLE
Better tab design and swipes

### ISSUE THREAD

**Issue by bikram-agarwal** [adithya321/Countdown#4]
1. Right now the app has two tabs - One with the notification icon, another with the crossed out notification icon. Those icons are kinda misleading / confusing. You should use better iconography there. Maybe just use text there, instead of icons. Name the tabs - Upcoming and Past.

2. Now that users can swipe away events from countdown list (and I submitted a request to allow that in the countup list too), the app needs some better way to handle swiping between the two tabs, to prevent accidental event deletion. Maybe replace the tabs at the top with [bottom nav bar](https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-usage).

**Comment by adithya321** [comment]
Fixed by commit [e8cbe5afeeb40935b428ac14392145e61305761b](https://github.com/adithya321/Countdown/commit/e8cbe5afeeb40935b428ac14392145e61305761b)
